import { defineConfig, devices } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

// __dirname is not defined in ESM — derive it from import.meta.url.
const CONFIG_DIR = dirname(fileURLToPath(import.meta.url));

/**
 * RS-013 Phase 3 — Playwright config for real multi-server E2E.
 *
 * Replaces the ACMD-128 single-web config. Three dev servers are spawned
 * by `webServer` (reuseExistingServer in local dev) so the browser can
 * exercise the full login + onboarding flow against real vollos-core,
 * acmd-api, and acmd-web code. Only the Google SDK and the `POST
 * /auth/google` network boundary are mocked — see src/e2e/helpers/
 * google-mock.ts.
 *
 * RSA keys are generated by scripts/generate-e2e-keys.mjs (run lazily
 * from globalSetup for the first invocation and cached on disk at
 * ./.e2e/keys.json so repeated test runs stay deterministic). The PEMs
 * are read here to pass into the vollos-core dev server and the
 * Playwright process so the test-JWT signer and the JWKS endpoint share
 * the same key pair.
 *
 * DB state is reset ONCE before the whole suite via globalSetup (see
 * src/e2e/helpers/db-reset.ts). Individual tests are responsible for
 * cleaning up any rows they create that later tests would conflict
 * with (currently only Scenario 1 → Scenario 2 share the DB; we issue
 * different emails / google_ids per scenario to avoid conflict).
 */

// Resolve RSA keys up front — playwright.config.ts runs as part of the
// initial Playwright process, so synchronous FS access is fine here. The
// helper generates + caches the pair if missing.
const keysPath = new URL('./.e2e/keys.json', `file://${CONFIG_DIR}/`).pathname;
type KeyBundle = { privateKey: string; publicKey: string };
let keys: KeyBundle;
try {
  keys = JSON.parse(readFileSync(keysPath, 'utf-8'));
} catch {
  execSync(`node "${CONFIG_DIR}/scripts/generate-e2e-keys.mjs"`, { stdio: 'inherit' });
  keys = JSON.parse(readFileSync(keysPath, 'utf-8'));
}

/**
 * Local postgres hostname — the dev servers + Playwright process run on
 * the host, not inside docker, so we override the `.env`'s docker
 * hostname (`postgres` / `vollos-core-postgres`) with 127.0.0.1:5432
 * (the published port from docker-compose.yml).
 */
const LOCAL_PG_URL =
  'postgresql://vollos:devpassword123@127.0.0.1:5432/vollos_dev';
const ACMD_LOCAL_PG_URL =
  'postgresql://acmd_user:devpassword123@127.0.0.1:5432/vollos_dev';

// Propagate to the Playwright process itself so test-jwt.ts can import
// the private key and db-reset.ts can connect to postgres.
process.env['AUTH_RSA_PRIVATE_KEY'] = keys.privateKey;
process.env['AUTH_RSA_PUBLIC_KEY'] = keys.publicKey;
process.env['E2E_DATABASE_URL'] = LOCAL_PG_URL;

export default defineConfig({
  testDir: './src/e2e',
  // RS-013: this config boots vollos-core auth-service alongside acmd-api,
  // which in turn forces acmd-api to verify JWTs via JWKS (VOLLOS_AUTH_URL
  // is set in the webServer block below). The legacy pages.e2e.ts +
  // workflow.e2e.ts suites sign tokens via /api/v1/auth/test-login using
  // acmd-api's local RSA pair — incompatible with JWKS mode. Until those
  // two suites migrate to the vollos-core login flow (tracked for a
  // follow-up task), only the RS-013 login suite runs through this
  // config. Owners can still invoke the legacy suites with a custom
  // PLAYWRIGHT_TEST_MATCH override.
  testMatch: process.env['PLAYWRIGHT_TEST_MATCH'] ?? '**/rs-013-*.e2e.ts',
  timeout: 60_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  forbidOnly: !!process.env['CI'],
  retries: process.env['CI'] ? 2 : 0,
  workers: 1,
  reporter: [['html', { open: 'never' }], ['list']],
  globalSetup: './src/e2e/helpers/db-reset.ts',
  use: {
    baseURL: 'http://localhost:3003',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: [
    // vollos-core auth-service :3004 — issues real RS256 tokens + JWKS
    {
      command: 'pnpm --filter @vollos/auth-service dev',
      cwd: '/home/ipon/workspace/vollos-ai/vollos-core',
      url: 'http://localhost:3004/health',
      timeout: 120_000,
      reuseExistingServer: !process.env['CI'],
      stdout: 'pipe',
      stderr: 'pipe',
      env: {
        PORT: '3004',
        NODE_ENV: 'development',
        AUTH_RSA_PRIVATE_KEY: keys.privateKey,
        AUTH_RSA_PUBLIC_KEY: keys.publicKey,
        DATABASE_URL: LOCAL_PG_URL,
        AUTH_DATABASE_URL: LOCAL_PG_URL,
        AUTH_CORS_ORIGINS: 'http://localhost:3003',
        // Real Google verification is never hit because Playwright
        // intercepts POST /auth/google before it reaches the handler,
        // but the factory still requires a non-empty string at boot.
        GOOGLE_CLIENT_ID: 'e2e-placeholder.apps.googleusercontent.com',
      },
    },
    // acmd-api :3001 — JWKS verify + /me + /onboarding
    {
      command: 'pnpm --filter @acmd/api dev',
      cwd: '/home/ipon/workspace/vollos-ai/acmd',
      url: 'http://localhost:3001/health',
      timeout: 120_000,
      reuseExistingServer: !process.env['CI'],
      stdout: 'pipe',
      stderr: 'pipe',
      env: {
        ACMD_API_PORT: '3001',
        NODE_ENV: 'development',
        // acmd-api fetches JWKS from vollos-core (NOT local keys).
        VOLLOS_AUTH_URL: 'http://localhost:3004',
        DATABASE_URL: ACMD_LOCAL_PG_URL,
        ACMD_GOOGLE_CLIENT_ID: 'e2e-placeholder.apps.googleusercontent.com',
        // Still required by the test-login endpoint path even though we
        // do not exercise it here — falling back to a placeholder keeps
        // module init happy.
        ACMD_JWT_SECRET: 'e2e-placeholder-jwt-secret-not-used-rs256',
        // 32-byte hex string consumed by @acmd/crypto.
        ACMD_ENCRYPTION_KEY:
          '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
        GOOGLE_CLOUD_PROJECT: 'e2e-placeholder',
        VERTEX_AI_LOCATION: 'us-central1',
        // T-118-E2E R3 — trust X-Forwarded-For from Playwright loopback so each
        // test scenario can mint a unique source IP via context.extraHTTPHeaders.
        // Without this, all scenarios share the same TCP peer IP (127.0.0.1)
        // and the per-IP/hour rate limit (5 attempts) is consumed by negative
        // tests before happy-path tests get a chance. SAFE because this env
        // is only set by the Playwright webServer block — production uses an
        // explicit operator-configured allowlist.
        TRUSTED_PROXY_IPS: '127.0.0.1,::1',
      },
    },
    // acmd-web :3003 — SPA dev server
    {
      command: 'pnpm --filter @acmd/web dev',
      cwd: '/home/ipon/workspace/vollos-ai/acmd',
      url: 'http://localhost:3003',
      timeout: 120_000,
      reuseExistingServer: !process.env['CI'],
      stdout: 'pipe',
      stderr: 'pipe',
      env: {
        // vite reads VITE_* at dev server start — keep these aligned
        // with apps/web/.env.local.
        VITE_API_BASE_URL: 'http://localhost:3001',
        VITE_VOLLOS_AUTH_URL: 'http://localhost:3004',
        VITE_GOOGLE_CLIENT_ID: 'e2e-placeholder.apps.googleusercontent.com',
      },
    },
  ],
});
